# Generated by Django 5.1.5 on 2025-02-06 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_tag_comment_post_tags_vote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='nombre',
            new_name='name',
        ),
    ]
